version: '3.8'

services:
  app:
    build: .
    image: devsugou/lunch-app:latest
    ports:
      - "8080:8080"
    depends_on:
      # - redis
      - postgres
    volumes:
      - /home/msugo/work_lunch/logs:/app/log

  # redis:
  #   image: "redis:latest"
  #   ports:
  #     - "6379:6379"

  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mysecretpassword"
      POSTGRES_DB: "lunch_db"
    volumes:
      - /home/msugo/work_lunch/postgres-data:/var/lib/postgresql/data
      # - ./src/main/resources/db/01_ddl.sql:/docker-entrypoint-initdb.d/01_ddl.sql
      # - ./src/main/resources/db/02_dml.sql:/docker-entrypoint-initdb.d/02_dml.sql